### ISSUE TITLE
Support httpd-ex for other versions then only RHEL-8

### ISSUE THREAD

**Issue by phracek** [sclorg/httpd-ex#35]
In the template.json file, we have hardcoded RHEL-8 here: https://github.com/sclorg/httpd-ex/blob/master/openshift/templates/httpd.json#L95

It would be nice to parametrize it or branch this project to support RHEL-8, and RHEL9.
Like it is done here: https://github.com/sclorg/nginx-ex/blob/master/openshift/templates/nginx.json#L96 https://github.com/sclorg/nginx-ex/blob/master/openshift/templates/nginx.json#L227

WDYT? Does it make sense? Are there some steps needed from OpenShift team?
@yselkowitz @bparees @hhorak

**Comment by yselkowitz** [comment]
Makes sense to me.  All you need to do is modify this template to accept and use the additional parameter.   Just note that the default must remain RHEL8 (`2.4-ubi8`) until development begins on a version of OpenShift which uses a RHEL9 RHCOS by default.  Once the changes have been tested and committed to this repo, they will be synced automatically into OpenShift's library, from where they will be synced into the next version of OpenShift.  No specific actions are required by the OpenShift team for such a change.
